name: Coastlens
favicon: null
layout_spectrum: 0.02591054909862578
typography_spectrum: 0.49631412979215384
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.03184946672990918
  lightness: 0.043769427575170994
  saturation: 0.6756911969278008
  rhythmicContrast: 0.8900398106779903
purpose: []
